# Generated by Django 4.2.30 on 2026-04-13 16:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recording',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.RemoveField(
            model_name='anomaly',
            name='resolved',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='audio_recording',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='user',
        ),
        migrations.AddField(
            model_name='anomaly',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_anomalies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='species',
            name='conservation_status',
            field=models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered')], default='LC', max_length=2),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='flagged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_anomalies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recording',
            name='confidence_score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='recording',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recordings.location'),
        ),
        migrations.AlterField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
