# Generated by Django 4.2.30 on 2026-04-14 05:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recordings', '0002_alter_recording_options_remove_anomaly_resolved_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomaly',
            options={'ordering': ['-flagged_at'], 'verbose_name_plural': 'Anomalies'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location_name']},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['common_name'], 'verbose_name_plural': 'Species'},
        ),
        migrations.AddField(
            model_name='anomaly',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='recordings/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='recording',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recording',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='flagged_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recording',
            name='confidence_score',
            field=models.FloatField(help_text='Confidence that the species was correctly identified (0.0–1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='recording',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to='recordings.location'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='recordings.species'),
        ),
    ]
