# Generated by Django 4.2.30 on 2026-04-15 09:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_alter_anomaly_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anomaly',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recording',
            options={'ordering': ['-date_recorded']},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['common_name']},
        ),
        migrations.RemoveField(
            model_name='anomaly',
            name='flagged_at',
        ),
        migrations.RemoveField(
            model_name='anomaly',
            name='flagged_by',
        ),
        migrations.RemoveField(
            model_name='anomaly',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='anomaly',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='anomaly',
            name='status',
        ),
        migrations.RemoveField(
            model_name='location',
            name='region',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='anomaly',
            name='flagged_anomaly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recording',
            name='date_recorded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recording',
            name='record_type',
            field=models.CharField(choices=[('human_observation', 'Human Observation'), ('machine_observation', 'Machine Observation'), ('preserved_specimen', 'Preserved Specimen'), ('material_sample', 'Material Sample')], default='human_observation', max_length=20),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='recording',
            name='confidence_score',
            field=models.IntegerField(default=0, help_text='Confidence score from 0 to 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='recording',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='recordings.location'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='recordings.species'),
        ),
        migrations.AlterField(
            model_name='species',
            name='conservation_status',
            field=models.CharField(choices=[('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EX', 'Extinct')], default='VU', max_length=2),
        ),
    ]
