# Generated by Django 4.2.30 on 2026-04-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0004_alter_anomaly_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomaly',
            name='flagged_anomaly',
        ),
        migrations.AddField(
            model_name='anomaly',
            name='status',
            field=models.CharField(choices=[('resolved', 'Resolved'), ('under_review', 'Under Review'), ('open', 'Open')], default='open', max_length=20),
        ),
    ]
