# Generated by Django 4.2.30 on 2026-04-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0005_remove_anomaly_flagged_anomaly_anomaly_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='reason',
            field=models.CharField(choices=[('misidentification', 'Misidentification'), ('data_error', 'Data Error'), ('unusual_location', 'Unusual Location'), ('other', 'Other')], max_length=20),
        ),
    ]
