# Generated by Django 4.2.30 on 2026-04-18 10:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recordings', '0006_alter_anomaly_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('flagged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_name', models.CharField(blank=True, max_length=200)),
                ('record_type', models.CharField(choices=[('HO', 'Human Observation'), ('MO', 'Machine Observation'), ('PS', 'Preserved Specimen'), ('MS', 'Material Sample'), ('OTHER', 'Other')], default='HO', max_length=20)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='recordings/%Y/%m/')),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='0.00 = no confidence, 1.00 = certain', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('notes', models.TextField(blank=True)),
                ('is_anomaly', models.BooleanField(db_index=True, default=False)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='recording',
            name='location',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='species',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['scientific_name'], 'verbose_name_plural': 'species'},
        ),
        migrations.AddField(
            model_name='species',
            name='is_native',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='species',
            name='not_native',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='species',
            name='common_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='species',
            name='conservation_status',
            field=models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('DD', 'Data Deficient'), ('NE', 'Not Evaluated')], default='NE', max_length=2),
        ),
        migrations.AlterField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='Anomaly',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Recording',
        ),
        migrations.AddField(
            model_name='audiorecording',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recordings', to='recordings.species'),
        ),
        migrations.AddField(
            model_name='anomalyflag',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='recordings.audiorecording'),
        ),
        migrations.AddIndex(
            model_name='audiorecording',
            index=models.Index(fields=['-recorded_at'], name='recordings__recorde_6627c3_idx'),
        ),
        migrations.AddIndex(
            model_name='audiorecording',
            index=models.Index(fields=['species', '-recorded_at'], name='recordings__species_1596e0_idx'),
        ),
    ]
